relable scripts to rocknix

diff --git a/packages/rocknix/sources/scripts/rocknix-settings b/packages/rocknix/sources/scripts/rocknix-settings
--- a/packages/rocknix/sources/scripts/rocknix-settings
+++ b/packages/rocknix/sources/scripts/rocknix-settings
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# batocera-settings can mimic batoceraSettings.py
+# rocknix-settings can mimic rocknixSettings.py
 # goal: abolish this python script, it's useless for the sake of the load feature only
 #       get a more user friendly environment for setting, getting and saving keys
 #
@@ -22,16 +22,16 @@
 # boolean value.
 
 # Examples:
-# 'batocera-settings --command load --key wifi.enabled' will print out 0 or 1
-# 'batocera-settings --command write --key wifi.ssid -value "This is my NET"' will set 'wlan.ssid=This is my NET'
-# 'batocera-settings enable wifi.ssid' will remove # from  configfile (activate)
-# 'batocera-settings disable wifi.enabled' will set key wifi.enabled=0
-# 'botocera-settings /myown/config.file --command status --key my.key' will output status of own config.file and my.key 
+# 'rocknix-settings --command load --key wifi.enabled' will print out 0 or 1
+# 'rocknix-settings --command write --key wifi.ssid -value "This is my NET"' will set 'wlan.ssid=This is my NET'
+# 'rocknix-settings enable wifi.ssid' will remove # from  configfile (activate)
+# 'rocknix-settings disable wifi.enabled' will set key wifi.enabled=0
+# 'rocknix-settings /myown/config.file --command status --key my.key' will output status of own config.file and my.key 
 
 # by cyperghost - 2019/12/30
 
 ##### INITS #####
-BATOCERA_CONFIGFILE="/storage/.config/system/configs/system.cfg"
+ROCKNIX_CONFIGFILE="/storage/.config/system/configs/system.cfg"
 COMMENT_CHAR_SEARCH="[#|;]"
 COMMENT_CHAR="#"
 ##### INITS #####
@@ -44,10 +44,10 @@ function get_config() {
     #Otherwise strip till the equal-char to obtain value
     local val
     local ret
-    val="$(grep -E -m1 "^\s*$1\s*=" $BATOCERA_CONFIGFILE)"
+    val="$(grep -E -m1 "^\s*$1\s*=" $ROCKNIX_CONFIGFILE)"
     ret=$?
     if [[ $ret -eq 1 ]]; then 
-        val="$(grep -E -m1 "^$COMMENT_CHAR_SEARCH\s*$1\s*=" $BATOCERA_CONFIGFILE)"
+        val="$(grep -E -m1 "^$COMMENT_CHAR_SEARCH\s*$1\s*=" $ROCKNIX_CONFIGFILE)"
         ret=$?
         [[ $ret -eq 0 ]] && val=$COMMENT_CHAR
     else
@@ -60,17 +60,17 @@ function get_config() {
 
 function set_config() {
      #Will search for first key.name at beginning of line and write value to it
-     sed -i "1,/^\(\s*$1\s*=\).*/s//\1$2/" "$BATOCERA_CONFIGFILE"
+     sed -i "1,/^\(\s*$1\s*=\).*/s//\1$2/" "$ROCKNIX_CONFIGFILE"
 }
 
 function uncomment_config() {
      #Will search for first Comment Char at beginning of line and remove it
-     sed -i "1,/^$COMMENT_CHAR_SEARCH\(\s*$1\)/s//\1/" "$BATOCERA_CONFIGFILE"
+     sed -i "1,/^$COMMENT_CHAR_SEARCH\(\s*$1\)/s//\1/" "$ROCKNIX_CONFIGFILE"
 }
 
 function comment_config() {
      #Will search for first key.name at beginning of line and add a comment char to it
-     sed -i "1,/^\(\s*$1\)/s//$COMMENT_CHAR\1/" "$BATOCERA_CONFIGFILE"
+     sed -i "1,/^\(\s*$1\)/s//$COMMENT_CHAR\1/" "$ROCKNIX_CONFIGFILE"
 }
 
 function check_argument() {
@@ -140,10 +140,10 @@ function main() {
 
     #Filename parsed?
     if [[ -f "$1" ]]; then
-        BATOCERA_CONFIGFILE="$1"
-        shift 
+        ROCKNIX_CONFIGFILE="$1"
+        shift
     else
-       [[ -f "$BATOCERA_CONFIGFILE" ]] || { echo "not found: $BATOCERA_CONFIGFILE" >&2; exit 2; }
+       [[ -f "$ROCKNIX_CONFIGFILE" ]] || { echo "not found: $ROCKNIX_CONFIGFILE" >&2; exit 2; }
     fi
 
     #How much arguments are parsed, up to 6 then it is the long format
@@ -176,8 +176,8 @@ function main() {
         "stat"|"status")
             val="$(get_config $keyvalue)"
             ret=$?
-            [[ -f "$BATOCERA_CONFIGFILE" ]] && echo "ok: found '$BATOCERA_CONFIGFILE'" >&2 || echo "error: not found '$BATOCERA_CONFIGFILE'" >&2
-            [[ -w "$BATOCERA_CONFIGFILE" ]] && echo "ok: r/w file '$BATOCERA_CONFIGFILE'" >&2 || echo "error: r/o file '$BATOCERA_CONFIGFILE'" >&2
+            [[ -f "$ROCKNIX_CONFIGFILE" ]] && echo "ok: found '$ROCKNIX_CONFIGFILE'" >&2 || echo "error: not found '$ROCKNIX_CONFIGFILE'" >&2
+            [[ -w "$ROCKNIX_CONFIGFILE" ]] && echo "ok: r/w file '$ROCKNIX_CONFIGFILE'" >&2 || echo "error: r/o file '$ROCKNIX_CONFIGFILE'" >&2
             [[ -z "$val" && $ret -eq 1 ]] && echo "error: '$keyvalue' not found!" >&2
             [[ -z "$val" && $ret -eq 0 ]] && echo "error: '$keyvalue' is empty - use 'comment' command to retrieve" >&2
             [[ "$val" == "$COMMENT_CHAR" ]] && echo "error: '$keyvalue' is commented $COMMENT_CHAR!" >&2 && val=
@@ -187,7 +187,7 @@ function main() {
 
         "set"|"write"|"save")
             #Is file write protected?
-            [[ -w "$BATOCERA_CONFIGFILE" ]] || { echo "r/o file: $BATOCERA_CONFIGFILE" >&2; exit 2; }
+            [[ -w "$ROCKNIX_CONFIGFILE" ]] || { echo "r/o file: $ROCKNIX_CONFIGFILE" >&2; exit 2; }
             #We can comment line above to erase keys, it's much saver to check if a value is setted
             [[ -z "$newvalue" ]] && echo "error: '$keyvalue' needs value to be setted" >&2 && exit 1
 
@@ -254,7 +254,7 @@ function main() {
 # Attention the unset is needed to eliminate first argument (python basefile)
 
 if [[ "${#@}" -eq 1 && "$1" =~ "mimic_python" ]]; then
-   #batoceraSettings.py fob
+   #rocknixSettings.py fob
    readarray -t arr <<< "$1"
    unset arr[0]
 else
