still file based but much less

diff --git a/packages/sysutils/system-utils/sources/scripts/input_sense b/packages/sysutils/system-utils/sources/scripts/input_sense
--- a/packages/sysutils/system-utils/sources/scripts/input_sense
+++ b/packages/sysutils/system-utils/sources/scripts/input_sense
@@ -12,11 +12,8 @@ set -o pipefail
 #   This script listens to input events and takes actions.
 ###
 LOCK_FILE="/tmp/input_sense.lock"
-FN_A_PRESSED_FILE="/tmp/FN_A_PRESSED.state"
-FN_B_PRESSED_FILE="/tmp/FN_B_PRESSED.state"
-touch "$FN_A_PRESSED_FILE" "$FN_B_PRESSED_FILE"
-echo "false" >"$FN_A_PRESSED_FILE"
-echo "false" >"$FN_B_PRESSED_FILE"
+KEY_GUIDE_FILE="/tmp/key_guide_output.json"
+touch "$KEY_GUIDE_FILE"
 swaymsg bar mode overlay
 
 # Exit if another instance is already running
@@ -29,7 +26,6 @@ trap 'rm -f "$LOCK_FILE"; exit' EXIT HUP INT TERM
 
 cleanup() {
   ${DEBUG} && log $0 "Cleaning up"
-  reset_stuck_state
   rm -rf "$LOCK_FILE"
 }
 
@@ -126,8 +122,6 @@ RELEASE='value 0'
 FN_A_PRESSED=false
 FN_B_PRESSED=false
 FN_A_PRESS_TIME=0
-FN_A_LONG_PRESS_TRIGGERED=false
-FN_A_TIMER_PID=""
 
 ### Allow actions to be overriden in system.cfg
 FN_A_ACTION_UP="$(get_setting key.function.a.up)"
@@ -219,22 +213,6 @@ execute_action() {
   fi
 }
 
-reset_stuck_state() {
-  local current_time=$(date +%s)
-  local fn_a_time=$(stat -c %Y "$FN_A_PRESSED_FILE" 2>/dev/null || echo 0)
-  local fn_b_time=$(stat -c %Y "$FN_B_PRESSED_FILE" 2>/dev/null || echo 0)
-
-  if [ $((current_time - fn_a_time)) -gt 10 ]; then # 10 seconds timeout
-    echo "false" >"$FN_A_PRESSED_FILE"
-    FN_A_PRESSED=false
-  fi
-
-  if [ $((current_time - fn_b_time)) -gt 10 ]; then # 10 seconds timeout
-    echo "false" >"$FN_B_PRESSED_FILE"
-    FN_B_PRESSED=false
-  fi
-}
-
 toggle_waybar() {
   ${DEBUG} && log $0 "Attempting to toggle waybar"
 
@@ -258,6 +236,35 @@ toggle_waybar() {
   swaymsg bar mode $new_state
   ${DEBUG} && log $0 "Toggled waybar to $new_state"
 }
+
+update_key_guide() {
+  source /storage/.config/waybar/hotkeys/current-hotkeys
+
+  KEY_GUIDE_NONE=$(echo $KEY_GUIDE_NONE)
+  KEY_GUIDE_1=$(echo $KEY_GUIDE_1)
+  KEY_GUIDE_2=$(echo $KEY_GUIDE_2)
+  KEY_GUIDE_3=$(echo $KEY_GUIDE_3)
+
+  local tmp_file="${KEY_GUIDE_FILE}.tmp"
+
+  if [ "$FN_A_PRESSED" = true ] && [ "$FN_B_PRESSED" = false ]; then
+    echo "{\"text\": \"$KEY_GUIDE_1\", \"class\": \"key-guide-1\"}" >"$tmp_file"
+  elif [ "$FN_A_PRESSED" = false ] && [ "$FN_B_PRESSED" = true ]; then
+    echo "{\"text\": \"$KEY_GUIDE_2\", \"class\": \"key-guide-2\"}" >"$tmp_file"
+  elif [ "$FN_A_PRESSED" = true ] && [ "$FN_B_PRESSED" = true ]; then
+    echo "{\"text\": \"$KEY_GUIDE_3\", \"class\": \"key-guide-3\"}" >"$tmp_file"
+  else
+    echo "{\"text\": \"$KEY_GUIDE_NONE\", \"class\": \"key-guide-none\"}" >"$tmp_file"
+  fi
+
+  if ! mv "$tmp_file" "${KEY_GUIDE_FILE}"; then
+    echo "Failed to update key guide file" >&2
+    rm -f "$tmp_file"
+    exit 1
+  fi
+}
+
+update_key_guide
 
 ### Search the system for useful devices to monitor for inputs.
 get_devices() {
@@ -311,8 +318,6 @@ mkcontroller 2>/dev/null || :
   done
   wait
 ) | while read line; do
-  reset_stuck_state
-
   case ${line} in
   ${CONTROLLER_DISCONNECTED})
     ${DEBUG} && log $0 "Reloading due to ${CONTROLLER_DEVICE} reattach..."
@@ -326,7 +331,6 @@ mkcontroller 2>/dev/null || :
     if [[ "${line}" =~ ${PRESS} ]]; then
       ${DEBUG} && log $0 "${FUNCTION_MODIFIER_A_EVENT}: Pressed"
       FN_A_PRESSED=true
-      echo "true" >"$FN_A_PRESSED_FILE"
       FN_A_PRESS_TIME=$(date +%s)
     elif [[ "${line}" =~ ${RELEASE} ]]; then
       ${DEBUG} && log $0 "${FUNCTION_MODIFIER_A_EVENT}: Released"
@@ -341,20 +345,19 @@ mkcontroller 2>/dev/null || :
       fi
 
       FN_A_PRESSED=false
-      echo "false" >"$FN_A_PRESSED_FILE"
       FN_A_PRESS_TIME=0
     fi
+    update_key_guide
     ;;
   ${FUNCTION_MODIFIER_B_EVENT})
     if [[ "${line}" =~ ${PRESS} ]]; then
       ${DEBUG} && log $0 "${FUNCTION_MODIFIER_B_EVENT}: Pressed"
       FN_B_PRESSED=true
-      echo "true" >"$FN_B_PRESSED_FILE"
     elif [[ "${line}" =~ ${RELEASE} ]]; then
       ${DEBUG} && log $0 "${FUNCTION_MODIFIER_B_EVENT}: Released"
       FN_B_PRESSED=false
-      echo "false" >"$FN_B_PRESSED_FILE"
     fi
+    update_key_guide
     ;;
   ${FUNCTION_VOLUME_UP_EVENT})
     execute_action up
