refactored and shellchecked get_git

diff --git a/scripts/get_git b/scripts/get_git
--- a/scripts/get_git
+++ b/scripts/get_git
@@ -1,3 +1,4 @@
+#!/bin/bash
 # SPDX-License-Identifier: GPL-2.0
 # Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)
 
@@ -11,135 +12,89 @@
 # PKG_GIT_CLONE_DEPTH (optional) history to clone, must be a number
 # PKG_GIT_SUBMODULE_DEPTH (optional) history of submodules to clone, must be a number
 
-_get_repo_already_downloaded() {
-  if [ -d "${PACKAGE}" ]; then
-    (
-      cd "${PACKAGE}"
-      _get_repo_clean
-      [ -n "$(git ls-remote . | grep -m1 HEAD | awk "/^${PKG_VERSION}/ {print \$1;}")" ] || die "ERROR: ${PACKAGE}: failed to determine git HEAD"
-      [ "${PKG_URL}" = "$(git remote get-url origin)" ] || die "ERROR: ${PACKAGE}: failed to obtain URL of origin"
-      [ -z "${PKG_GIT_CLONE_BRANCH}" ] && exit 0
-      [ "${PKG_GIT_CLONE_BRANCH}" = "$(git branch | grep ^\* | cut -d ' ' -f2)" ] || die "ERROR: ${PACKAGE}: failed to determine current git branch"
-      exit 0
-    )
-    return
-  else
-    return 1
-  fi
-}
+set -e
+set -o pipefail
 
-_get_repo_clean() {
+_clean_repo() {
   git clean -fdx
   git checkout -- .
 }
 
-# Latest file already present, exit now...
-_get_repo_already_downloaded && exit 0
+_repo_exists_and_valid() {
+  if [[ -d "${PACKAGE}" ]]; then
+    pushd "${PACKAGE}" > /dev/null
+    _clean_repo || return 1
 
+    if ! git ls-remote . | grep -q -m1 "^${PKG_VERSION}"; then
+      echo "ERROR: ${PACKAGE}: failed to determine git HEAD" >&2
+      return 1
+    fi
+
+    if [[ "${PKG_URL}" != "$(git remote get-url origin)" ]]; then
+      echo "ERROR: ${PACKAGE}: failed to obtain URL of origin" >&2
+      return 1
+    fi
+
+    if [[ -n "${PKG_GIT_CLONE_BRANCH}" && "${PKG_GIT_CLONE_BRANCH}" != "$(git rev-parse --abbrev-ref HEAD)" ]]; then
+      echo "ERROR: ${PACKAGE}: failed to determine current git branch" >&2
+      return 1
+    fi
+
+    popd > /dev/null
+    return 0
+  fi
+  return 1
+}
+
+_get_repo() {
+  local git_params="--recursive --shallow-submodules --filter=tree:0"
+  [[ -n "${PKG_GIT_CLONE_BRANCH}" ]] && git_params+=" --branch ${PKG_GIT_CLONE_BRANCH}"
+  [[ "${PKG_GIT_CLONE_SINGLE}" == "yes" ]] && git_params+=" --single-branch"
+
+  if [[ -n "${PKG_GIT_CLONE_DEPTH}" ]]; then
+    if [[ "${PKG_GIT_CLONE_DEPTH}" =~ ^[0-9]+$ ]]; then
+      git_params+=" --depth ${PKG_GIT_CLONE_DEPTH}"
+    else
+      echo "ERROR: PKG_GIT_CLONE_DEPTH is not a number! (${PKG_GIT_CLONE_DEPTH})" >&2
+      return 1
+    fi
+  fi
+
+  git clone "${git_params}" "${PKG_URL}" "${PACKAGE}" || return 1
+}
+
+_update_submodules() {
+  git submodule update --init --recursive "${GIT_SUBMODULE_PARAMS}" || return 1
+}
+
+# Check if repo already exists and is valid
+_repo_exists_and_valid && exit 0
+
+# Acquire lock on source dir and re-check
 lock_source_dir "${1}"
+_repo_exists_and_valid && exit 0
 
-# Check again in case of concurrent access - if nothing needs to be downloaded, exit now...
-_get_repo_already_downloaded && exit 0
-
-# At this point, we need to download something...
+# If not valid, proceed to get the repo
 build_msg "CLR_GET" "GET" "${1} (git)" "indent"
 
-pkg_lock_status "GETPKG" "${PKG_NAME}" "unpack" "processing package repository..."
-
+# Remove stale stamps
 rm -f "${STAMP_URL}" "${STAMP_SHA}"
 
-GIT_CLONE_PARAMS="--recursive --shallow-submodules --filter=tree:0"
-GIT_SUBMODULE_PARAMS=""
-
-[ -n "${PKG_GIT_CLONE_BRANCH}" ] && GIT_CLONE_PARAMS="${GIT_CLONE_PARAMS} --branch ${PKG_GIT_CLONE_BRANCH}"
-[ "${PKG_GIT_CLONE_SINGLE}" = "yes" ] && GIT_CLONE_PARAMS="${GIT_CLONE_PARAMS} --single-branch"
-
-if [ -n "${PKG_GIT_CLONE_DEPTH}" ]; then
-  if [[ "${PKG_GIT_CLONE_DEPTH}" =~ ^[0-9]+$ ]]; then
-    GIT_CLONE_PARAMS="${GIT_CLONE_PARAMS} --depth ${PKG_GIT_CLONE_DEPTH}"
-  else
-    die "ERROR: PKG_GIT_CLONE_DEPTH is not a number! (${PKG_GIT_CLONE_DEPTH})"
-  fi
+# Clone or update the repository
+if ! _repo_exists_and_valid; then
+  _get_repo || exit 1
+elif [[ -n "${GIT_DIR}" ]] && [[ "${GIT_DIR}" != "${PACKAGE}" ]]; then
+  mv "${GIT_DIR}" "${PACKAGE}" || exit 1
 fi
 
-if [ -n "${PKG_GIT_SUBMODULE_DEPTH}" ]; then
-  if [[ "${PKG_GIT_SUBMODULE_DEPTH}" =~ ^[0-9]+$ ]]; then
-    GIT_SUBMODULE_PARAMS="${GIT_SUBMODULE_PARAMS} --depth ${PKG_GIT_SUBMODULE_DEPTH}"
-  else
-    die "ERROR: PKG_GIT_SUBMODULE_DEPTH is not a number! (${PKG_GIT_SUBMODULE_DEPTH})"
-  fi
-fi
+pushd "${PACKAGE}" > /dev/null
+git reset --hard "${PKG_VERSION}" || exit 1
+_update_submodules || exit 1
+popd > /dev/null
 
-GIT_FOUND="no"
-opwd="$(pwd)"
-for d in "${SOURCES}/${1}/${1}-"* ; do
-  if [ -d "${d}/.git" ]; then
-    if [ "${GIT_FOUND}" = "no" ]; then
-      cd "${d}"
-      if [ "${PKG_URL}" = "$(git remote get-url origin)" ]; then
-        if [[ -z "${PKG_GIT_CLONE_BRANCH}" ]] || [[ $(git branch | grep "^\* ${PKG_GIT_CLONE_BRANCH}$" | wc -l) -eq 1 ]]; then
-          GIT_FOUND="yes"
-          GIT_DIR="${d}"
-          _get_repo_clean
-        elif [ $(git branch | grep "^  ${PKG_GIT_CLONE_BRANCH}$" | wc -l) -eq 1 ]; then
-          GIT_FOUND="yes"
-          GIT_DIR="${d}"
-          _get_repo_clean
-          git checkout "${PKG_GIT_CLONE_BRANCH}"
-        elif [ $(git branch -a | grep "^  remotes/origin/${PKG_GIT_CLONE_BRANCH}$" | wc -l) -eq 1 ]; then
-          GIT_FOUND="yes"
-          GIT_DIR="${d}"
-          _get_repo_clean
-          git checkout -b "${PKG_GIT_CLONE_BRANCH}" "origin/${PKG_GIT_CLONE_BRANCH}"
-        else
-          build_msg "CLR_CLEAN" "DELETE" "(${d})"
-          cd "${opwd}"
-          rm -rf "${d}"
-        fi
-        if [ "${GIT_FOUND}" = "yes" ]; then
-          build_msg "CLR_GET" "GIT PULL" "${1}"
-
-          # If there is an error with 'git pull' or updating the submodules, just reclone
-          # NOTE: we run the submodule update twice if the clone already
-          #       exists - but deduplicating would complicate the logic quite a lot and
-          #       the second time is almost a no-op
-          if ! git pull || ! git submodule update --init --recursive ${GIT_SUBMODULE_PARAMS}; then
-              cd "${opwd}"
-              build_msg "CLR_CLEAN" "DELETE" "(${d})"
-              GIT_FOUND=NO
-              rm -rf "${d}"
-          fi
-          cd "${opwd}"
-        fi
-      else
-        build_msg "CLR_CLEAN" "DELETE" "(${d})"
-        cd "${opwd}"
-        rm -rf "${d}"
-      fi
-    fi
-  else
-    build_msg "CLR_CLEAN" "DELETE" "(${d})"
-    rm -rf "${d}"
-  fi
-done
-cd "${opwd}"
-
-if [ "${GIT_FOUND}" = "no" ]; then
-  build_msg "CLR_GET" "GIT CLONE" "${1}"
-  git clone ${GIT_CLONE_PARAMS} "${PKG_URL}" "${PACKAGE}"
-elif [ ! "${GIT_DIR}" = "${PACKAGE}" ]; then
-  mv "${GIT_DIR}" "${PACKAGE}"
-fi
-
-( cd "${PACKAGE}"
-  [ $(git log --oneline --pretty=tformat:"%H" | grep "^${PKG_VERSION}" | wc -l) -eq 1 ] || die "There is no commit '${PKG_VERSION}' on branch '$(git branch | grep ^\* | cut -d ' ' -f2)' of package '${1}'! Aborting!"
-  git reset --hard "${PKG_VERSION}"
-  build_msg "CLR_GET" "GIT SUBMODULE" "${1}"
-  git submodule update --init --recursive ${GIT_SUBMODULE_PARAMS}
-)
-
-GIT_SHA="$(git ls-remote "${PACKAGE}" | grep -m1 HEAD | awk '{print $1;}')"
-
-if [ -n "${PKG_GIT_SHA}" -a "${PKG_GIT_SHA}" != "${GIT_SHA}" ]; then
-  build_msg "CLR_WARNING" "WARNING" "Incorrect git hash in repository: got ${GIT_SHA}, wanted ${PKG_GIT_SHA}"
+# Verify the git hash
+GIT_SHA="$(git ls-remote "${PACKAGE}" | grep -m1 HEAD | awk '{print $1;}')" || exit 1
+if [[ -n "${PKG_GIT_SHA}" && "${PKG_GIT_SHA}" != "${GIT_SHA}" ]]; then
+  build_msg "CLR_WARNING" "WARNING" "Incorrect git hash in repository: got ${GIT_SHA}, wanted ${PKG_GIT_SHA}" >&2
+  exit 1
 fi
